#!/usr/bin/env python3
"""
gen_version.py — write src/version.h from git describe

Usage:
    python tools/gen_version.py

Run automatically by the Makefile before each build.

If this is a git repository with tags, the version string looks like:
    v1.2.3          (exact tag)
    v1.2.3-7-gabc1234   (7 commits after v1.2.3)
    v1.2.3-7-gabc1234-dirty  (uncommitted changes)

Without git (or no tags), falls back to "0.1.0-dev".
"""

import subprocess
import os
import sys


def get_version() -> str:
    """Return a version string from git describe, or a fallback."""
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        # git not available, repo has no tags, or not a git repo
        return "0.1.0-dev"


def main() -> int:
    version = get_version()

    # Write to src/version.h relative to this script's parent directory
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "src", "version.h")

    content = f"""\
/* version.h — generated by tools/gen_version.py — DO NOT EDIT MANUALLY
 * Run:  python tools/gen_version.py
 * Or:   make          (the Makefile runs this automatically)
 */
#pragma once
#define GUARDIAN_VERSION "{version}"
"""

    with open(out_path, "w") as f:
        f.write(content)

    print(f"guardian version : {version}")
    print(f"wrote            : {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
