/*
 * cli.c — Command-line interface dispatch
 *
 * Key C concepts demonstrated here:
 *   - argc/argv — reading command-line arguments
 *   - strcmp()  — comparing strings (not == which compares pointers, not content)
 *   - printf vs fprintf(stderr) — stdout for output, stderr for errors
 *   - Returning exit codes from main() — 0=success, non-zero=failure
 */

#include "cli.h"
#include "config.h"
#include "logger.h"
#include "service.h"
#include "supervisor.h"
#include "ipc.h"
#include "version.h"        /* GUARDIAN_VERSION — generated by tools/gen_version.py */
#include "platform/platform.h"

#include <stdio.h>    /* printf, fprintf, fopen, fseek, fread, fwrite, fclose */
#include <string.h>   /* strcmp, strstr, strncpy */
#include <stdlib.h>   /* EXIT_SUCCESS, EXIT_FAILURE */
#include <signal.h>   /* signal(), SIGINT, SIGTERM */

/* Default IPC path — must match the default in ipc.c.
 * On Windows, platform_ipc_connect() converts this to \\.\pipe\guardian.sock */
#define DEFAULT_IPC_PATH "/tmp/guardian.sock"

/* ==========================================================================
 * Forward declarations for internal command handlers
 *
 * 'static' means these functions are private to this file.
 * We declare them here so cli_run() can call them even though their
 * definitions appear later in the file. This is called a "forward declaration."
 * ==========================================================================
 */
static int cmd_start(int argc, char *argv[]);
static int cmd_version(void);
static int cmd_logs(int argc, char *argv[]);
static void print_usage(const char *program_name);

/* ==========================================================================
 * Helpers for printing service info (Phase 1 milestone output)
 * ==========================================================================
 */

/*
 * extract_json_str — pull a string value from a JSON object
 *
 * Finds "key":"<value>" in 'json' and copies <value> into 'out'.
 * Returns 1 on success, 0 if the key wasn't found.
 *
 * This is a minimal hand-written parser — only works for simple string values.
 * A real JSON parser handles escaping, nesting, etc. For our fixed protocol
 * this is completely sufficient and much simpler than a library.
 */
static int extract_json_str(const char *json, const char *key,
                              char *out, int out_size) {
    /* Build the search pattern: "key":" */
    char pattern[64];
    snprintf(pattern, sizeof(pattern), "\"%s\":\"", key);

    const char *start = strstr(json, pattern);
    if (!start) return 0;

    start += strlen(pattern);  /* skip past the pattern to the value */
    const char *end = strchr(start, '"');
    if (!end) return 0;

    int len = (int)(end - start);
    if (len >= out_size) len = out_size - 1;
    strncpy(out, start, len);
    out[len] = '\0';
    return 1;
}

/*
 * print_status_response — format the JSON status response as a table
 *
 * Input example:
 *   {"ok":true,"services":[{"name":"api","state":"RUNNING","pid":1234,...}]}
 *
 * Output:
 *   SERVICE          STATE      PID       RESTARTS  UPTIME
 *   api              RUNNING    1234      0         1m 23s
 *   worker           BACKOFF    0         2         -
 */
static void print_status_response(const char *resp) {
    if (!strstr(resp, "\"ok\":true")) {
        fprintf(stderr, "guardian: daemon returned an error\n");
        return;
    }

    printf("\n  %-16s %-10s %-9s %-9s %s\n",
           "SERVICE", "STATE", "PID", "RESTARTS", "UPTIME");
    printf("  %-16s %-10s %-9s %-9s %s\n",
           "-------", "-----", "---", "--------", "------");

    /* Walk through each service object in the "services" array.
     * We find each '{' that starts a service, extract fields, then
     * advance to the next one. */
    const char *p = strstr(resp, "\"services\":[");
    if (!p) { printf("  (no services)\n\n"); return; }
    p += strlen("\"services\":[");

    while ((p = strchr(p, '{')) != NULL) {
        /* Find the closing brace for this service object */
        const char *end = strchr(p, '}');
        if (!end) break;

        /* Extract a copy of just this service's JSON object */
        char obj[512];
        int len = (int)(end - p + 1);
        if (len >= (int)sizeof(obj)) len = (int)sizeof(obj) - 1;
        strncpy(obj, p, len);
        obj[len] = '\0';

        char name[64]  = "-";
        char state[32] = "-";
        char pid[16]   = "-";
        char retries[8] = "0";
        char uptime_s[16] = "0";

        extract_json_str(obj, "name",    name,     sizeof(name));
        extract_json_str(obj, "state",   state,    sizeof(state));
        extract_json_str(obj, "pid",     pid,      sizeof(pid));
        extract_json_str(obj, "retries", retries,  sizeof(retries));
        extract_json_str(obj, "uptime_s",uptime_s, sizeof(uptime_s));

        /* Format uptime as "Xm Ys" */
        char uptime_fmt[32] = "-";
        long secs = atol(uptime_s);
        if (secs > 0) {
            if (secs >= 3600)
                snprintf(uptime_fmt, sizeof(uptime_fmt), "%ldh %ldm",
                         secs/3600, (secs%3600)/60);
            else if (secs >= 60)
                snprintf(uptime_fmt, sizeof(uptime_fmt), "%ldm %lds",
                         secs/60, secs%60);
            else
                snprintf(uptime_fmt, sizeof(uptime_fmt), "%lds", secs);
        }

        printf("  %-16s %-10s %-9s %-9s %s\n",
               name, state, pid, retries, uptime_fmt);

        p = end + 1;
    }
    printf("\n");
}

static const char *restart_policy_name(RestartPolicy p) {
    switch (p) {
        case RESTART_NEVER:      return "never";
        case RESTART_ON_FAILURE: return "on_failure";
        case RESTART_ALWAYS:     return "always";
        default:                 return "unknown";
    }
}

static const char *health_type_name(HealthCheckType t) {
    switch (t) {
        case HEALTH_NONE:    return "none";
        case HEALTH_TCP:     return "tcp";
        case HEALTH_HTTP:    return "http";
        case HEALTH_COMMAND: return "command";
        default:             return "unknown";
    }
}

/*
 * print_loaded_config — Phase 1 milestone: show what was parsed
 *
 * Prints a human-readable summary of everything config_load() found.
 * In later phases, this is replaced by actually starting the services.
 */
static void print_loaded_config(const SupervisorContext *ctx) {
    printf("\n");
    printf("  Guardian — loaded configuration\n");
    printf("  ================================\n");

    if (ctx->log_file[0]) {
        printf("  Log file   : %s\n", ctx->log_file);
    } else {
        printf("  Log file   : (stdout only)\n");
    }

    if (ctx->ipc_socket[0]) {
        printf("  IPC socket : %s\n", ctx->ipc_socket);
    }

    printf("  Services   : %d\n\n", ctx->service_count);

    for (int i = 0; i < ctx->service_count; i++) {
        const ServiceConfig *cfg = &ctx->services[i].cfg;

        printf("  [%s]\n", cfg->name);
        printf("    command    : %s", cfg->command);
        if (cfg->args[0]) printf(" %s", cfg->args);
        printf("\n");

        if (cfg->working_dir[0]) {
            printf("    working dir: %s\n", cfg->working_dir);
        }

        printf("    autostart  : %s\n", cfg->autostart ? "yes" : "no");
        printf("    restart    : %s\n", restart_policy_name(cfg->restart_policy));
        if (cfg->max_retries == 0) {
            printf("    max retries: unlimited\n");
        } else {
            printf("    max retries: %d\n", cfg->max_retries);
        }

        printf("    backoff    : %dms base, %dms max\n",
               cfg->backoff_base_ms, cfg->backoff_max_ms);

        if (cfg->has_health_check) {
            printf("    health     : %s -> %s (every %ds, timeout %ds, threshold %d)\n",
                   health_type_name(cfg->health.type),
                   cfg->health.target,
                   cfg->health.interval_s,
                   cfg->health.timeout_s,
                   cfg->health.unhealthy_threshold);
        } else {
            printf("    health     : none\n");
        }

        if (cfg->env_count > 0) {
            printf("    env vars   : %d set\n", cfg->env_count);
        }

        printf("\n");
    }
}

/* ==========================================================================
 * Command handlers
 * ==========================================================================
 */

static int cmd_start(int argc, char *argv[]) {
    /*
     * 'guardian start' requires exactly one argument: the config file path.
     * argv[0] = "guardian", argv[1] = "start", argv[2] = "config-file"
     * So argc must be at least 3.
     */
    if (argc < 3) {
        fprintf(stderr, "Usage: guardian start <config-file>\n");
        return EXIT_FAILURE;
    }

    const char *config_path = argv[2];

    LOG_INFO("guardian", "Loading configuration from '%s'", config_path);

    /*
     * Declare the SupervisorContext on the stack.
     *
     * Stack allocation: the variable lives in the current function's
     * stack frame. It is automatically freed when the function returns.
     * No malloc(), no free(). For a struct this size (~50KB with 64 services),
     * this is perfectly safe — the default stack size is typically 1-8MB.
     *
     * The config_load() function takes a pointer to ctx and fills it in.
     */
    SupervisorContext ctx;
    ConfigError err = config_load(config_path, &ctx);

    if (err != CONFIG_OK) {
        fprintf(stderr, "guardian: failed to load config: %s\n",
                config_error_string(err));
        return EXIT_FAILURE;
    }

    LOG_INFO("guardian", "Configuration loaded: %d service(s)", ctx.service_count);

    /* Print the loaded config so the user can verify before processes start */
    print_loaded_config(&ctx);

    /* Re-initialize the logger with the log file path from config (if set) */
    if (ctx.log_file[0] != '\0') {
        logger_close();
        logger_init(ctx.log_file);
    }

    /* Hand off to the supervisor — this runs until Ctrl+C */
    supervisor_run(&ctx);

    return EXIT_SUCCESS;
}

static int cmd_version(void) {
    /*
     * GUARDIAN_VERSION comes from src/version.h, written by tools/gen_version.py
     * at the start of each build. If git tags exist it looks like "v1.2.3";
     * otherwise it falls back to "0.1.0-dev".
     *
     * __DATE__ and __TIME__ are C preprocessor macros expanded to string literals
     * at compile time: "Apr  4 2026" and "10:23:01". They capture the exact
     * moment the binary was built, which is useful for bug reports.
     */
    printf("guardian %s (built " __DATE__ " " __TIME__ ")\n", GUARDIAN_VERSION);
    return EXIT_SUCCESS;
}

/* ==========================================================================
 * guardian logs — follow a service's log file (like tail -f)
 * ==========================================================================
 */

/*
 * g_logs_running — set to 0 by the signal handler on Ctrl+C / SIGTERM.
 *
 * We use the standard signal() function here (not sigaction) because this is
 * a short-lived CLI command, not a long-running daemon. signal() is simpler
 * and perfectly adequate for this use case.
 *
 * 'volatile' tells the compiler: this variable may change outside normal
 * program flow (i.e., from a signal handler). Without volatile, the compiler
 * might cache g_logs_running in a register and never re-read it from memory,
 * causing the follow loop to run forever even after Ctrl+C.
 */
static volatile int g_logs_running = 1;

static void logs_signal_handler(int signum) {
    (void)signum;
    g_logs_running = 0;
}

/*
 * cmd_logs — tail and follow a service's stdout log file
 *
 * Usage: guardian logs <service-name> <config-file>
 *
 * Behaviour:
 *   1. Load the config to find the service's stdout_log path.
 *   2. Print the last ~8 KB of the file (enough for the most recent entries).
 *   3. Poll every 100 ms for new content and print it as it arrives.
 *   4. Exit cleanly on Ctrl+C or SIGTERM.
 *
 * This is essentially what `tail -f` does — a simple but genuinely useful
 * tool that demonstrates file I/O and polling loops.
 */
static int cmd_logs(int argc, char *argv[]) {
    if (argc < 4) {
        fprintf(stderr,
            "Usage: guardian logs <service-name> <config-file>\n"
            "\n"
            "Example:\n"
            "  guardian logs web-api guardian.ini\n"
            "\n"
            "Note: the service must have 'stdout_log' set in the config.\n");
        return EXIT_FAILURE;
    }

    const char *service_name = argv[2];
    const char *config_path  = argv[3];

    /* Load config to find the service's log file path */
    SupervisorContext ctx;
    if (config_load(config_path, &ctx) != CONFIG_OK) {
        fprintf(stderr, "guardian: failed to load config '%s'\n", config_path);
        return EXIT_FAILURE;
    }

    /* Find the service by name and get its stdout_log path */
    char log_path[GUARDIAN_MAX_PATH] = "";
    for (int i = 0; i < ctx.service_count; i++) {
        if (strcmp(ctx.services[i].cfg.name, service_name) == 0) {
            strncpy(log_path, ctx.services[i].cfg.stdout_log,
                    sizeof(log_path) - 1);
            break;
        }
    }

    if (log_path[0] == '\0') {
        fprintf(stderr,
            "guardian: service '%s' has no stdout_log configured\n"
            "         Add this to [%s] in %s:\n"
            "           stdout_log = /var/log/guardian/%s.log\n",
            service_name, service_name, config_path, service_name);
        return EXIT_FAILURE;
    }

    /* Install signal handlers so Ctrl+C exits cleanly */
    signal(SIGINT,  logs_signal_handler);
    signal(SIGTERM, logs_signal_handler);

    /*
     * Open the log file. If it doesn't exist yet (service hasn't started),
     * wait for it to appear — this mirrors the behaviour of `tail -f`.
     */
    FILE *f = NULL;
    while (!f && g_logs_running) {
        f = fopen(log_path, "rb");
        if (!f) {
            fprintf(stderr, "guardian: waiting for '%s'...\n", log_path);
            platform_sleep_ms(500);
        }
    }
    if (!f) return EXIT_SUCCESS;  /* Ctrl+C while waiting */

    /*
     * Seek to show only the tail of the file — the last ~8 KB.
     * For a freshly-started service the whole file fits; for a long-running
     * one we skip old history and show only the most recent entries.
     *
     * If we start mid-file, we skip forward to the next newline so we
     * always print complete lines (never a truncated first line).
     */
    long tail_bytes = 8192;
    if (fseek(f, 0, SEEK_END) == 0) {
        long size = ftell(f);
        long start = (size > tail_bytes) ? size - tail_bytes : 0;
        fseek(f, start, SEEK_SET);
        if (start > 0) {
            /* skip to the start of the next complete line */
            int c;
            while ((c = fgetc(f)) != EOF && c != '\n') { /* advance */ }
        }
    }

    fprintf(stderr, "==> %s <==\n", log_path);

    /*
     * THE FOLLOW LOOP
     *
     * fread() reads as many bytes as are available up to sizeof(buf).
     * When there's nothing new, it returns 0 — we hit the current EOF.
     * clearerr() clears the EOF flag so the next fread() tries again.
     *
     * This 100 ms poll is the same interval as the supervisor event loop,
     * which means new log lines appear within 100 ms of being written.
     */
    char buf[4096];
    size_t n;
    while (g_logs_running) {
        while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
            fwrite(buf, 1, n, stdout);
            fflush(stdout);
        }
        clearerr(f);
        platform_sleep_ms(100);
    }

    fclose(f);
    return EXIT_SUCCESS;
}

static void print_usage(const char *program_name) {
    fprintf(stderr,
        "Usage: %s <command> [options]\n"
        "\n"
        "Commands:\n"
        "  start  <config-file>   Start the supervisor\n"
        "  stop   [config-file]   Stop a running supervisor\n"
        "  status [config-file]   Show service status\n"
        "  logs   <service> <config-file>   Tail a service's log file\n"
        "  version                Print version information\n"
        "\n"
        "Example:\n"
        "  %s start guardian.ini\n"
        "\n",
        program_name, program_name);
}

/* ==========================================================================
 * Public entry point
 * ==========================================================================
 */

int cli_run(int argc, char *argv[]) {
    /*
     * argc is always at least 1 (argv[0] is the program name).
     * If argc == 1, the user ran just "guardian" with no arguments.
     */
    if (argc < 2) {
        print_usage(argv[0]);
        return EXIT_FAILURE;
    }

    const char *command = argv[1];

    /*
     * IMPORTANT: In C, comparing strings with '==' compares POINTERS —
     * whether two variables point to the same memory address. That is almost
     * never what you want. To compare string CONTENT, always use strcmp().
     * strcmp(a, b) returns 0 if a and b have the same characters.
     */
    if (strcmp(command, "start") == 0) {
        return cmd_start(argc, argv);
    }

    if (strcmp(command, "stop") == 0) {
        /* Read config to find the ipc_socket path, or use the default */
        const char *path = DEFAULT_IPC_PATH;
        SupervisorContext ctx;
        if (argc >= 3 && config_load(argv[2], &ctx) == CONFIG_OK
                      && ctx.ipc_socket[0] != '\0') {
            path = ctx.ipc_socket;
        }
        char resp[256];
        if (!ipc_send_command(path, "{\"cmd\":\"stop\"}", resp, sizeof(resp))) {
            return EXIT_FAILURE;
        }
        printf("Guardian stopped.\n");
        return EXIT_SUCCESS;
    }

    if (strcmp(command, "status") == 0) {
        const char *path = DEFAULT_IPC_PATH;
        SupervisorContext ctx;
        if (argc >= 3 && config_load(argv[2], &ctx) == CONFIG_OK
                      && ctx.ipc_socket[0] != '\0') {
            path = ctx.ipc_socket;
        }
        char resp[IPC_MSG_MAX];
        if (!ipc_send_command(path, "{\"cmd\":\"status\"}", resp, sizeof(resp))) {
            return EXIT_FAILURE;
        }
        /* Pretty-print the status response */
        print_status_response(resp);
        return EXIT_SUCCESS;
    }

    if (strcmp(command, "logs") == 0) {
        return cmd_logs(argc, argv);
    }

    if (strcmp(command, "version") == 0) {
        return cmd_version();
    }

    fprintf(stderr, "guardian: unknown command '%s'\n\n", command);
    print_usage(argv[0]);
    return EXIT_FAILURE;
}
