/* version.h — generated by tools/gen_version.py — DO NOT EDIT MANUALLY
 * Run:  python tools/gen_version.py
 * Or:   make          (the Makefile runs this automatically)
 */
#pragma once
#define GUARDIAN_VERSION "0.1.0-dev"
